on:
  push:
    branches:
      - main
      
jobs:
  android:
    name: android
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.8'
    - run: flutter pub get
    - run: dart run ffigen
    - run: flutter build apk
    - run: flutter build appbundle

  ios:
    name: ios
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.8'
        architecture: x64
    - run: flutter pub get
    - run: dart run ffigen
    - run: flutter build ios --release --no-codesign

  windows:
    name: windows
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        flutter-version: '3.3.8'
     - run: dart run ffigen
     - run: flutter pub run msix:create
